FORMAT: 1A
HOST: http://agendacs.apiblueprint.org/

# LibraryBookSeatSystem

图书管理系统api详解。

# Group Users

关于用户的Api介绍。

## User Register [/users]

### Register User [POST]
+ parameter
    + ID (required, string) - 用户学号
    + name (required, string) - 用户姓名
    + password (required, string) - 经md5加密后的用户密码
    + email (required, string) - 用户邮箱
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)

        {
            "ID" : "15331234",
            "name": "hza",
            "password": "9b5299c1bcb585a7",
            "email": "123@qq.com",
        }

+ Response 201 (application/json)
    
        {
            "errorcode": 0,
            "errorinformation": ""
        }

## User Login [/v1/user/login]

### User Login [POST]
+ parameter
    + ID (required, string) - 用户学号
    + password (required, string) - 经md5加密后的用户密码
    + name (optional, string) - 用户姓名
    + email (optional, string) - 用户邮箱
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息


+ Request (application/json)

        {
            "ID": "15331234",
            "password":"9b5299c1bcb585a71"
        }

+ Response 201 (application/json)

        {
            "errorcode": 0,
            "errorinformation": ""
            "name":"hza",
            "email":"123@qq.com",
        }

## User Logout [/v1/user/logout]

### User Logout [GET]
+ parameter
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request
    + Header
        cookie:{ "ID" : "15331234" }

+ Response 200 (application/json)

        {
            "errorcode": 0,
            "errorinformation": ""
        }

# Group Seats

关于座位的api介绍。

**PS:之后操作必须在登陆后才能进行，请求必须含有Cookie字段！** <br>
**cookie : { "ID" : "15331234" }**

## Show Valid Time Intervals [/v1/timeintervals]

### Show Valid Time Intervals [GET]
+ parameter
    + timeintervals (optional, [(string, int)]) - 可选择的预约开始时间和剩余座位数
    + begintime (optional, string) - 预约开始时间
    + endtime (optional, string) - 预约结束时间
    + restseatsnum (optional, int) - 对应时间剩余座位
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request
    + Header
        cookie:{ "ID" : "15331234" }

+ Response 201 (application/json)

        {
            "errorcode": 0,
            "errorinformation": "",
            "timeintervals": [
                {
                    "begintime": "2018-04-08 10:00:00",
                    "endtime": "2018-04-08 11:00:00",
                    "restseatsnum": 200
                },
                {
                    "begintime": "2018-04-08 11:00:00",
                    "endtime": "2018-04-08 12:00:00",
                    "restseatsnum": 180
                },
                {
                    "begintime": "2018-04-08 12:00:00",
                    "endtime": "2018-04-08 13:00:00",
                    "restseatsnum": 260
                }
            ]
        }

## Show Seats Information [/v1/seats]

### Show Seats Information [GET]
+ parameter
    + begintime (required, string) - 预约开始时间
    + seatinfo (optional, [int]) - 代表座位是否被预约(0是未预约)
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)
    + Header
        cookie:{ "ID" : "15331234" }
    
    + Body
        {
            "begintime": "2018-04-08 10:00:00"
        }

+ Response 201 (application/json)

        {
            "errorcode": 0,
            "errorinformation": "",
            "seatinfo": [
                0,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0
            ]
        }

## Seat Book [/v1/seat/book]

### Seat Book [POST]
+ parameter
    + begintime (required, string) - 预约开始时间
    + seatID (optional, int) - 座位ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)
    + Header
        cookie:{ "ID" : "15331234" }
    
    + Body
        {
            "begintime": "2018-04-08 10:00:00",
            "endtime": "2018-04-08 13:00:00",
            "seatID": 20
        }

+ Response 201 (application/json)

        {
            "errorcode": 0,
            "errorinformation": ""
        }

## Seat Unbook [/v1/seat/unbook]

### Seat Unbook [POST]
+ parameter
    + begintime (required, string) - 预约开始时间
    + endtime (optional, string) - 预约结束时间
    + seatID (optional, int) - 座位ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)
    + Header
        cookie:{ "ID" : "15331234" }
    
    + Body
        {
            "begintime": "2018-04-08 10:00:00",
            "endtime": "2018-04-08 11:00:00",
            "seatID": 22
        }

+ Response 201 (application/json)

        {
            "errorcode": 15,
            "errorinformation": "Can't unbook another seats!"
        }

## Seat Signin [/v1/seat/signin]

使用微信小程序！！先不实现

### Seat Signin [GET]
+ parameter
    + seatID (optional, int) - 座位ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)
    + Header
        cookie:{ "ID" : "15331234" }
    
    + Body
        {
            "seatID": 22
        }

+ Response 201 (application/json)

        {
            "errorcode": 21,
            "errorinformation": "Current time isn't match book begin time!"
        }

## Seat Signout [/v1/seat/signout]

使用微信小程序！！先不实现

### Seat Signout [GET]
+ parameter
    + seatID (optional, int) - 座位ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)
    + Header
        cookie:{ "ID" : "15331234" }
    
    + Body
        {
            "seatID": 22
        }

+ Response 201 (application/json)

        {
            "errorcode": 22,
            "errorinformation": "Current time isn't match book end time!"
        }