FORMAT: 1A
HOST: http://agendacs.apiblueprint.org/

# LibraryBookSeatSystem

图书管理系统api详解。

# Group Users

关于用户的Api介绍。

## User Register [/v1/users]

### User Register [POST]
+ parameter
    + openID (required, string) - 用户微信ID
    + netID (required, string) - 用户学校内部ID
    + password (required, string) - 经md5加密后的用户密码
    + school (required, string) - 用户学校
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)

        {
            "openID" : "123456789",
            "netID" : "12341234"
            "password": "9b5299c1bcb585a7",
            "school": "Sun Yat-sen University"
        }

+ Response 201 (application/json)
    
        {
            "errorcode": 0,
            "errorinformation": "",
        }

### User Info [GET]
+ parameter
    + openID (required, string) - 用户微信ID
    + school (optional, string) - 用户学校
    + violation (optional, int) - 违规次数
    + bookseatinfos (optional, [(string, string, int, int)]) - 用户预约和签到的信息
    + begintime (optional, string) - 预约开始时间
    + endtime (optional, string) - 预约结束时间
    + seatID (optional, int) - 座位ID
    + seatinfo (optional, int) - 座位当前信息(0是未预约，1是已预约，2是已签到)
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)

        {
            "openID": "123456789"
        }

+ Response 200 (application/json)

        {
            "school": "Sun Yat-sen University",
            "voilation": 0,
            "bookseatinfos": [
                {
                    "begintime": "2018-04-08 10:00:00",
                    "endtime": "2018-04-08 11:00:00",
                    "seatID": 22,
                    "seatinfo": 2
                },
                {
                    "begintime": "2018-04-08 11:00:00",
                    "endtime": "2018-04-08 12:00:00",
                    "seatID": 22,
                    "seatinfo": 1
                }
            ],
            "errorcode": 0,
            "errorinformation": ""
        }
## User Login [/v1/user/login]
感觉不需要

### User Login [GET]
+ parameter
    + openID (required, string) - 用户微信ID
    + school (optional, string) - 用户学校
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息


+ Request (application/json)

        {
            "openID": "123456789"
        }

+ Response 201 (application/json)

        {
            "school": "Sun Yat-sen University",
            "errorcode": 0,
            "errorinformation": ""
        }

## User Logout [/v1/user/logout]
感觉不需要

### User Logout [GET]
+ parameter
    + openID (required, string) - 用户微信ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)

        {
            "openID": "123456789"
        }

+ Response 200 (application/json)

        {
            "errorcode": 0,
            "errorinformation": ""
        }


# Group Seats

关于座位的api介绍。

**PS:之后操作必须在登陆后才能进行，请求必须含有openID字段！** <br>

## Show Valid Time Intervals [/v1/timeintervals]

### Show Valid Time Intervals [GET]
+ parameter
    + openID (required, string) - 用户微信ID
    + timeintervals (optional, [(string, string, int)]) - 可选择的预约开始时间和剩余座位数
    + begintime (optional, string) - 预约开始时间
    + endtime (optional, string) - 预约结束时间
    + restseatsnum (optional, int) - 对应时间剩余座位
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息


+ Request (application/json)

        {
            "openID": "123456789"
        }

+ Response 200 (application/json)

        {
            "errorcode": 0,
            "errorinformation": "",
            "timeintervals": [
                {
                    "begintime": "2018-04-08 10:00:00",
                    "endtime": "2018-04-08 11:00:00",
                    "restseatsnum": 200
                },
                {
                    "begintime": "2018-04-08 11:00:00",
                    "endtime": "2018-04-08 12:00:00",
                    "restseatsnum": 180
                },
                {
                    "begintime": "2018-04-08 12:00:00",
                    "endtime": "2018-04-08 13:00:00",
                    "restseatsnum": 260
                }
            ]
        }

## Show Seats Information [/v1/seats]

### Show Seats Information [GET]
+ parameter
    + openID (required, string) - 用户微信ID
    + begintime (required, string) - 预约开始时间
    + endtime (required, string) - 预约结束时间
    + seatinfos (optional, [int]) - 代表座位是否被预约(0是未预约，1是已预约，2是已签到)
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)

        {
            "openID": "123456789",
            "begintime": "2018-04-08 10:00:00",
            "endtime": "2018-04-08 11:00:00"
        }

+ Response 200 (application/json)

        {
            "seatinfos": [
                0,
                1,
                1,
                1,
                0,
                0,
                0,
                2,
                0
            ],
            "errorcode": 0,
            "errorinformation": ""
        }

## Seat Book [/v1/seat/book]

### Seat Book [POST]
+ parameter
    + openID (required, string) - 用户微信ID
    + begintime (required, string) - 预约开始时间
    + endtime (required, string) - 预约结束时间
    + seatID (required, int) - 座位ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)

        {
            "openID": "123456789",
            "begintime": "2018-04-08 10:00:00",
            "endtime": "2018-04-08 11:00:00",
            "seatID": 20
        }

+ Response 201 (application/json)

        {
            "errorcode": 0,
            "errorinformation": ""
        }

## Seat Unbook [/v1/seat/unbook]

### Seat Unbook [POST]
+ parameter
    + openID (required, string) - 用户微信ID
    + begintime (required, string) - 预约开始时间
    + endtime (required, string) - 预约结束时间
    + seatID (required, int) - 座位ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)

        {
            "openID": "123456789",
            "begintime": "2018-04-08 10:00:00",
            "endtime": "2018-04-08 11:00:00",
            "seatID": 22
        }

+ Response 200 (application/json)

        {
            "errorcode": 107,
            "errorinformation": "学生信息与该座位不符"
        }

## Seat Signin [/v1/seat/signin]

### Seat Signin [GET]
+ parameter
    + openID (required, string) - 用户微信ID
    + seatID (required, int) - 座位ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)

        {
            "openID": "123456789",
            "seatID": 22
        }

+ Response 201 (application/json)

        {
            "errorcode": 0,
            "errorinformation": ""
        }

## Seat Signout [/v1/seat/signout]

暂时不需要

### Seat Signout [GET]
+ parameter
    + seatID (optional, int) - 座位ID
    + errorcode(optional, int) - 错误码
    + errorinformation(optional, string) - 错误信息

+ Request (application/json)
    + Header
        cookie:{ "ID" : "15331234" }
    
    + Body
        {
            "seatID": 22
        }

+ Response 201 (application/json)

        {
            "errorcode": 22,
            "errorinformation": "Current time isn't match book end time!"
        }